version: '3.8'

services:
  tickflow-mockserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    volumes:
      - ./:/tickflow-mockserver
      - /tickflow-mockserver/node_modules
