name: CD

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'README.md'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ticklabvn/tickflow-fe
  ORG_USERNAME: ${{ github.actor }}

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: tickflow-fe
          pull-request-header: 'Bot (:robot:) requested to create a new release on ${{ github.ref_name }}'

  build:
    name: Build
    needs: [release]
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.build == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup env and nginx-config file
        run: |
          echo VITE_BACKEND_URL=${{ vars.BACKEND_URL }} >> .env

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.ORG_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.release.outputs.tag_name }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  setup-nginx:
    name: Setup Nginx
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nginx-config file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: 'tickflowFE-nginx.config'
          target: '/etc/nginx/sites-enabled'

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [setup-nginx]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}

          script: |
            export SUDO=${{ secrets.VPS_PASSWORD }}
            echo $SUDO | sudo nginx -t
            echo $SUDO | sudo service nginx reload

            export CR_PAT=${{ secrets.GITHUB_TOKEN }}
            echo $CR_PAT | docker login ${{ env.REGISTRY }} -u ${{ env.ORG_USERNAME }} --password-stdin
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

            mkdir -p TickFlow-FE
            cd TickFlow-FE
            curl https://raw.githubusercontent.com/ticklabvn/tickflow-fe/main/docker-compose.yml -o docker-compose.yml
            docker compose stop tickflow-fe
            docker compose rm -f tickflow-fe
            docker compose up -d tickflow-fe
            docker logout ${{ env.REGISTRY }}
